export const allBanks = [
  "ICICI Bank Ltd",
  "Bank of Baroda",
  "Canara Bank",
  "Bank Of India",
  "Central Bank Of India",
  "State Bank Of India",
  "Punjab National Bank",
  "Bank of Maharastra",
  "Indian Bank",
  "Union Bank",
  "Indian Overseas Bank",
  "Axis Bank",
  "UCO Bank",
  "Allahabad Bank",
  "Punjab & Sind Bank",
  "Reserve Bank of India",
  "HDFC Bank",
  "IDBI Bank",
  "Corportation Bank",
];
